# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  admin_name: Daniele Stroppa
  admin_email: stroppad@amazon.com
  admin_password: Aws2015!
  domain_name: ''
  mailchimp_api_key: '' 
  mailchimp_list_id: ''
  secret_key_base: fce491206ae4880156ae62955e3613269d23a5e268c6407d3df5ff41533614642a0820464aefa44c23c68f236b85ca90daf0a5f11beac62522b9171f83dd2a2c

test:
  domain_name: '' 
  secret_key_base: 73d801d590ecb4e019413b60b88b55b26b2e79565a63d679b5ea53042a970eb21d5426f65e3e97b84ed714db9179b0a599047713bf39aef7ee42c9433e1a516e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  admin_name: <%= ENV["ADMIN_NAME"] %>
  admin_email: <%= ENV["ADMIN_EMAIL"] %>
  admin_password: <%= ENV["ADMIN_PASSWORD"] %>
  domain_name: ''
  mailchimp_api_key: ''
  mailchimp_list_id: '' 
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
